name: Launch tests for specified project
description: Install environment and launch tests

inputs:
  project:
    required: true
    description: For which project to launch tests - frontend or backend
  java-version:
    required: false
    description: Java version to use
    default: 11
  node-version:
    required: false
    description: Node version to use
    default: 20.16.0

runs:
  using: composite
  steps:
    # Install execution env for backend
    - name: Setup Java
      if: ${{ inputs.project }} == 'backend'
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: ${{ inputs.java-version }}
    - name: Launch tests
      shell: bash
      if: ${{ inputs.project }} == 'backend'
      run: cd back && pwd && mvn clean test

    # Install execution env for frontend
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: install dependencies
      shell: bas
      run: cd front && npm install
    - name: Launch tests
      shell: bas
      run: cd front && npm run test:prod