on:
  push: 
    branches: 
    - main
  
# cancel workflow when there is already one launched
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:

  sonarcloud-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
  
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 11

      - name: Compile project
        working-directory: back
        run: mvn clean package

      - uses: ./.github/actions/quality
        with:
          project_base_dir: 'back'
          organization: ${{ vars.SONAR_ORGANIZATION }}
          sonar_host: ${{ vars.SONAR_HOST }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_project_key: ${{ vars.SONAR_ORGANIZATION }}_backend
          sonar_options: >
            -Dsonar.sources=src/main/
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            
  sonarcloud-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
      - name: install dependencies
        working-directory: front
        run: npm install
      - name: Launch tests
        working-directory: front
        run: npm run test:prod
      - uses: ./.github/actions/quality
        with:
          project_base_dir: 'front'
          organization: ${{ vars.SONAR_ORGANIZATION }}
          sonar_host: ${{ vars.SONAR_HOST }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_project_key: ${{ vars.SONAR_ORGANIZATION }}_frontend
          sonar_options: >
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.exclusions=**/*.spec.ts,**/*test.ts,**/*.js
            -Dsonar.test.inclusions=**/*.spec.ts,**/*test.ts
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info

  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - uses: ./.github/actions/build-and-push
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: back
          tags: ${{ vars.DOCKERHUB_BACKEND_REPO }}:latest

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - uses: ./.github/actions/build-and-push
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          context: front
          tags: ${{ vars.DOCKERHUB_FRONTEND_REPO }}:latest