on:
  pull_request: 
    branches: 
      - dev
      - main

# cancel workflow when there is already one launched
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  quality-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4  
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 11
      
      # Tests
      - name: Launch tests
        working-directory: back
        run: mvn clean test

      # Quality
      - name: Compile project
        working-directory: back
        run: mvn clean package

      - uses: ./.github/actions/quality
        with:
          project_base_dir: 'back'
          organization: ${{ vars.SONAR_ORGANIZATION }}
          sonar_host: ${{ vars.SONAR_HOST }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_project_key: ${{ vars.SONAR_ORGANIZATION }}_backend
          sonar_options: >
            -Dsonar.sources=src/main/
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  quality-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4  
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
      - name: install dependencies
        working-directory: front
        run: npm install

      # Tests
      - name: Launch tests
        working-directory: front
        run: npm run test:prod

      # Quality
      - uses: ./.github/actions/quality
        with:
          project_base_dir: 'front'
          organization: ${{ vars.SONAR_ORGANIZATION }}
          sonar_host: ${{ vars.SONAR_HOST }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_project_key: ${{ vars.SONAR_ORGANIZATION }}_frontend
          sonar_options: >
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.exclusions=**/*.spec.ts,**/*test.ts,**/*.js
            -Dsonar.test.inclusions=**/*.spec.ts,**/*test.ts
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info