on:
  pull_request: 
    branches: 
      - dev

# cancel workflow when there is already one launched
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 11
      - name: Launch tests
        run: cd back && mvn clean test